apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: elasticsearch-logging
  labels:
    component: elasticsearch
    role: client
spec:
  type: ClusterIP
  selector:
    component: elasticsearch
    role: client
  ports:
  - name: http
    port: 9200
    protocol: TCP
