apiVersion: v1
kind: Service
metadata:
  name: fluentd
  namespace: kube-system
  labels:
spec:
  ports:
    - name: transport
      port: 24224
      protocol: TCP
      targetPort: 24224
  selector:
    k8s-app: fluentd
    component: fluentd
  type: ClusterIP

